# Generated by Django 5.1.1 on 2024-09-17 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_feelings_product_mood_product_mood_intensity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.CharField(default='Unknown', max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('feelings', models.CharField(default='Unknown', max_length=255)),
                ('mood_intensity', models.CharField(default='0000000000', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='feelings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mood_intensity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
