# Generated by Django 5.1.1 on 2024-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_moodentry_remove_product_feelings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='feelings',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood_intensity',
            field=models.CharField(default='', max_length=255),
        ),
    ]
